/* This is generated code, do not change this file manually.          */
/*                                                                    */
/* To change these definitions, alter road-colors.yaml and run:       */
/*                                                                    */
/* scripts/generate_road_colours.py > style/road-colors-generated.mss */
/*                                                                    */
@motorway-casing: #dc2a67;
@trunk-casing: #d83750;
@trunk-expressway-casing: #cf453c;
@primary-casing: #c45229;
@primary-expressway-casing: #b65e16;
@secondary-casing: #a66801;
@secondary-expressway-casing: #957100;
@tertiary-casing: #837800;
@tertiary-expressway-casing: #707d05;
@motorway-fill: #e892a2;
@trunk-fill: #f09d9e;
@trunk-expressway-fill: #f6a99c;
@primary-fill: #fab69c;
@primary-expressway-fill: #fcc49e;
@secondary-fill: #fcd1a2;
@secondary-expressway-fill: #fbdfa9;
@tertiary-fill: #f9edb3;
@tertiary-expressway-fill: #f7fabf;
@motorway-low-zoom: #e66e89;
@trunk-low-zoom: #ef7c82;
@trunk-expressway-low-zoom: #f48c7c;
@primary-low-zoom: #f69c79;
@primary-expressway-low-zoom: #f7ad78;
@secondary-low-zoom: #f5bd7b;
@secondary-expressway-low-zoom: #f1ce83;
@tertiary-low-zoom: #edde8e;
@tertiary-expressway-low-zoom: #e7ed9d;
@motorway-low-zoom-casing: #c24e6b;
@trunk-low-zoom-casing: #cb565f;
@trunk-expressway-low-zoom-casing: #d06053;
@primary-low-zoom-casing: #d26c46;
@primary-expressway-low-zoom-casing: #cf7a3a;
@secondary-low-zoom-casing: #ca882e;
@secondary-expressway-low-zoom-casing: #c19725;
@tertiary-low-zoom-casing: #b4a523;
@tertiary-expressway-low-zoom-casing: #a4b329;
@motorway-shield: #620728;
@trunk-shield: #620e1e;
@trunk-expressway-shield: #611714;
@primary-shield: #5e1f07;
@primary-expressway-shield: #592700;
@secondary-shield: #522e00;
@secondary-expressway-shield: #4a3500;
@tertiary-shield: #413a00;
@tertiary-expressway-shield: #364000;
